### ISSUE TITLE
reboot of worker node hosting kube-dns results in kube-dns CrashLoopBackOff mode

### ISSUE THREAD

**Issue by guillierf** [cloudfoundry-incubator/kubo-release#112]
kube-dns running on worker-node-1

procedure:
bosh ssh to worker-node-1
  then 'sudo su'
  then 'init 6'

result:
kube-dns will end up in CrashLoopBackOff mode:

$ kubectl get pod -o wide -n kube-system
NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
heapster-1569517067-d4jhg               1/1       Running            1          1h        10.200.5.4    10.40.207.98
kube-dns-3329716278-kzzn4               1/3       CrashLoopBackOff   26         32m       10.200.5.5    10.40.207.98
kubernetes-dashboard-1367211859-cq6rp   1/1       Running            0          32m       10.200.10.3   10.40.207.100
monitoring-influxdb-564852376-rmgr9     1/1       Running            0          1h        10.200.10.2   10.40.207.100

**Comment by akshaymankar** [comment]
@guillierf Thanks for reporting the issue, we'll prioritise this issue and work on it soon.

**Comment by akshaymankar** [comment]
@guillierf We've figured out what the issue is. This happens because there is a route which docker creates and we delete as part of deploying kubelet. But this does not happen if bosh doesn't restart the VM. The docker bosh-release already has a fix for this. We'll upgrade it and then this should not be an issue.

Until then, if a VM restarts on its own (without bosh bringing it back) you'd have to delete the route manually. Here is what you need to do on the worker VM:

```bash
docker0_addr=$(route -n | grep docker0 | awk '{print $1}')
docker0_gw=$(route -n | grep docker0 | awk '{print $2}')
docker0_netmask=$(route -n | grep docker0 | awk '{print $3}')
if [ "${docker0_addr}" != "" ]
then
  route del -net $docker0_addr gw $docker0_gw netmask $docker0_netmask dev docker0
fi
```

**Comment by guillierf** [comment]
@akshaymankar Thanks a lot !
