### ISSUE TITLE
Allow internal network to be configurable

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry-incubator/kubo-release#172]
Is it possible not to force 10.200.0.0/16 networks and make it configurable.

**Comment by BenChapman** [comment]
Hi @lnguyen,

It is possible from a Kubernetes point of view to make it configurable, and we'd be more than happy to accept a pull request with this change. Provided the default is kept to 10.200.0.0/16.

Otherwise this will be prioritised by the team in the future. We're unsure of when that will be.

Thanks,
Ben.
