### ISSUE TITLE
Flannel network get out of sync with docker bridge network (cni0)

### ISSUE THREAD

**Issue by carlo-colombo** [cloudfoundry-incubator/kubo-release#228]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After vms have been powered down for multiple days, after turning back on and issuing a `bosh recreate` to recreate the vms pods get stuck in `ContainerCreating`.

We found after recreation that the `flannel.1` and `cni0` /24 subnet don't match (10.200.78.0 and  10.200.29.1). The `cni0` has the same value that was there before power down.  

```
worker/ddbb5012-e134-4f3b-a7da-a1fd4976877e:/var/lib/cni/networks# ifconfig
cni0      Link encap:Ethernet  HWaddr 4e:d5:14:c4:c8:f3
          inet addr:10.200.29.1  Bcast:10.200.29.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

flannel.1 Link encap:Ethernet  HWaddr 2e:e3:38:5b:d5:69
          inet addr:10.200.78.0  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**What you expected to happen**:
Pods get rescheduled correctly, `cni0` and `flannel.1` should be on the same /24 subnet

**How to reproduce it (as minimally and precisely as possible)*
* Create a cluster with a single worker node
* Stop flanneld on the worker
* Extract the worker subnet value from `/run/flannel/subnet.env`- `FLANNEL_SUBNET`
* Remove the `/run/flannel/subnet.env`
* Remove worker subnet from etcd under `/coreos.com/network/subnets/` (this simulate expiration) 
* Restart `flanneld`
* Observe that `cni0` and `flannel.1` are not on the same /24 subnet

**Anything else we need to know?**:
We have been able to recover from this situation by stopping flanneld, remove the subnets from etcd and editing `/run/flannel/subnet.env` with the `cni0` subnet in  `FLANNEL_SUBNET`.

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
- Environment Info (`bosh -e <environment> environment`):
- Kubernetes version (`kubectl version`): v1.10.3
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): vpshere (but we think does not matter)

**Comment by carlo-colombo** [comment]
On further investigation it looks like the issue might be in `docker-boshrelease` 
- https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/0575caf4f946e14b4699a0f2d1a6d0ed92b5df2a/jobs/docker/templates/bin/ctl#L36-L45

The code linked above is not recreating the `cni0` bridge interface with the correct subnet

**Comment by alex-slynko** [comment]
More context from outside conversation:

1. VMs were hard powered off over the weekend
1. VMs got started using vCenter
1. workloads were down.
1. Bosh recreate each worker and master
1. Workload is down

cc @karampok

**Comment by karampok** [comment]
@carlo-colombo interesting case!

Summary:
- yes that [part](https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/0575caf4f946e14b4699a0f2d1a6d0ed92b5df2a/jobs/docker/templates/bin/ctl#L36-L45) in docker bosh release should allow the recreation of the cni0 bridge with the correct address.
- Nevertheless redo-ing the `ip addr add ${DOCKER_BRIDGE_CIDR} dev ${DOCKER_BRIDGE_NAME}` won't help a lot. The reason is that docker daemon itself tries to set up the cidr of the cni0 bridge.
You can observe that by setting docker debug flag to true and see the logs for the following message
```
time="2018-07-13T12:20:12.672870258Z" level=debug msg="Assigning address to bridge interface cni0: 10.200.92.1/24"
```
- As it seems  docker daemon stores some information in the `/var/vcap/data/docker/docker/` folder. There is a file `network/files/local-kv.db` which inside has "hard-coded" the original prefix

- Once you delete this file (or better the whole folder of `/var/vcap/data/docker/docker/`*) and do a `monit restart all` things should work as expected. This would have been  as the same as a `bosh recreate worker/X`

- One last thing to watch is that the ipam (ip management plugin of flannel) might have run out of ips in the above case (`/var/lib/cni/networks`).

**Comment by carlo-colombo** [comment]
> Once you delete this file (or better the whole folder of /var/vcap/data/docker/docker/*) and do a monit restart all things should work as expected. This would have been as the same as a bosh recreate worker/X

We tried to recreate the virtual machine, even deleting it from the vcenter, but the cni0 network always came back with the same address. We expect that something is stored in the persistent disks (worker's or master's), otherwise the `cni0` network should have came back with a different address at some point.

**Comment by karampok** [comment]
I found that this file "network/files/local-kv.db" has the persistent information about the prefix

**Comment by karampok** [comment]
@carlo-colombo is this issue still valid?

**Comment by iainsproat** [comment]
Closing for now.
