### ISSUE TITLE
Not Scheduling Workloads After Manually Re-starting VMs

### ISSUE THREAD

**Issue by leeloodub** [cloudfoundry-incubator/kubo-release#230]
**What happened**:
When restarting VMs by running bosh ssh -d $DEPLOYMENT_NAME -c "sudo shutdown -r now", we can see that all the VMs have started and worker node is ready. However, workloads are not getting scheduled.

**What you expected to happen**:
Workloads to get scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
Manually retart VMs through a sciprt, or console.

**Anything else we need to know?**:

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
- Environment Info (`bosh -e <environment> environment`):
- Kubernetes version (`kubectl version`): 1.10
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): GCP

**Comment by karampok** [comment]
Hi @leeloodub 

I could observe also the above behavior. This is happening only in GCP, and it is because 
gcp-provider makes the nodes by default not available because of the network
```
kubectl describe nodes |grep -A3 Condition
Conditions:
 
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   True    Mon, 01 Jan 0001 00:00:00 +0000   Tue, 24 Jul 2018 15:08:12 +0200   NoRouteCreated               Node created without a route
```

For that reason, we have to manually patch the node using the post-start script of bosh 
[link](https://github.com/cloudfoundry-incubator/kubo-release/blob/48f2dad57544c23457dd11b09f000ec955bd40fb/jobs/kubelet/templates/bin/post-start.erb#L44-L60l)

so the node is available in terms of networking
```
kubectl describe nodes |grep -A3 Condition
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Mon, 01 Jan 0001 00:00:00 +0000   Tue, 24 Jul 2018 15:08:14 +0200   NetworkProvidedByFlannel     Status manually modified by CFCR kubelet post-start
```
When we a do `bosh ssh -d cfc -c "sudo shutdown -r now" ` then the post start script does not run (therefore all the content of the post-start script is not executed, which can give a problem somewhere else also). Also the drain script is not also running which could be also of a problem.
 
Could you provide some more details why you need to  "manage" bosh vms outside bosh  (e.g. `bosh restart` or `bosh recreate`)?

**Comment by bu3** [comment]
Looking at our initial task now, this really only matters for vSphere. So, we can close this.
