### ISSUE TITLE
Need to change flannel network in Kubo-release

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/kubo-release#234]
hi is nay one change default flannel network in kubernets to  Project Calico (https://www.projectcalico.org/) (or) Cisco Contiv (http://contiv.github.io/) or any other CNIs.

Because Flannel network has many limitation in load-balancing, security and teannt etc.

Thanks in advance.

**Comment by karampok** [comment]
Hi @abhilash07 
could you describe a bit more your use case?
I am not sure I understand what is the issue?

Could also please follow the template?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context about the feature request here.

**Comment by karampok** [comment]
@abhilash07  please re-open the issue if needed
