### ISSUE TITLE
deploying cockpit kubernetes dashboard error

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/kubo-release#237]
hi i am trying to deploy cockpit kubernetes dashboard on kubo.

Deployment is successful, but login is error. I am new to kubernetes, any suggestions to overcome this error.
More over on gke kubernetes it is successfull. 
https://itnext.io/up-and-running-cockpit-for-google-kubernetes-engine-gke-4aca68f182bf
Screenshort.
![screen shot 2018-07-31 at 1 34 59 pm](https://user-images.githubusercontent.com/10971841/43437974-c92ec8cc-94c6-11e8-9bc2-e4aa757825ac.png)

Pod Logs
[logs-from-kubernetes-cockpit-in-kubernetes-cockpit-glqpr.txt](https://github.com/cloudfoundry-incubator/kubo-release/files/2243766/logs-from-kubernetes-cockpit-in-kubernetes-cockpit-glqpr.txt)

**Comment by martinpitt** [comment]
This was [fixed in kubernetes](https://github.com/kubernetes/kubernetes/pull/41775) last year already.

**Comment by tvs** [comment]
Please do not ignore the templates when filing issues. Without knowing what versions you're running, it's hard to tell if this is the result of an outdated Kubernetes version or if it's the result of yours/CFCR's configuration. As mentioned in the comment above, this may well be fixed with a more modern version of CFCR.
