### ISSUE TITLE
Restart kubelet on cfcr redeployment if relevant iaas changes were made

### ISSUE THREAD

**Issue by AlekseiMarkov** [cloudfoundry-incubator/kubo-release#284]
**What happened**/ **How to reproduce it (as minimally and precisely as possible)**::
steps to reproduce the problem:
1. deploy cfcr
2. modify/create a terraform override file that modifies worker iam permissions
3. redeploy cfcr
4. the worker role in aws _is_ updated, but kubelet is _not_ aware of the change. Only after manual restart of kubelet process on each worker everything works as expected

in our case the missing permission was ecr read permission. so after step 1 we got an error of our app deployment (kubelet couldn't pull the image from ecr)
after 3 - error didn't go away, as expected. only after manual kubelet restart

**What you expected to happen**:
cfcr understands that the delta-changes in terraform-files affect kubelet and restarts kubelet on all nodes.

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
Using environment '...' as client 'admin'
Name       Release(s)       Stemcell(s)                                    Config(s)        Team(s)  
my-name  bosh-dns/1.10.0  bosh-aws-xen-hvm-ubuntu-xenial-go_agent/170.9  1 cloud/default  -  
           bpm/0.13.0                                                      3 runtime/dns      
           cfcr-etcd/1.8.0                                                                    
           docker/33.0.0                                                                      
           kubo/0.25.0
- Environment Info (`bosh -e <environment> environment`):
Name      bosh-my-name
UUID      6e1c6e1d-d1e4-494b-b594-1a7002e79888  
Version   268.3.0 (00000000)  
CPI       aws_cpi  
Features  compiled_package_cache: disabled  
          config_server: enabled  
          local_dns: enabled  
          power_dns: disabled  
          snapshots: disabled  
User      admin
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):
aws

**Comment by tvs** [comment]
CFCR isn't really in the business of monitoring the infrastructure - that's all within BOSH's purview (and to some extent the Kubernetes Cloud Provider). In this case, the contents of the BOSH manifest did not change between deployments, so it's likely that step three (redeploy CFCR) didn't trigger any sort of update on the VM.

Since the IAM Profile exists _outside_ of both CFCR and BOSH, a better step three would have been to run `bosh restart worker` or perhaps `bosh ssh worker -c="sudo /var/vcap/bosh/bin/monit restart kubelet"` (to minimize the amount of work involved in simply restarting the process).

In any case, monitoring the IAAS infrastructure falls outside of CFCR's scope, so I'm going to go ahead and close this one out.
